### ISSUE TITLE
Look there

### ISSUE THREAD

**Issue by Raspifan2020** [HelmerLuzo/PlutoTV_HL#1]
Hi @HelmerLuzo,

**look there. This ashole is stolen m3u from overall!**

From Matts Huisman, Apsattv,FreeIPTV and from you... **you has the work, he copies and has in every startpage of his threads (3) an donation button**...

This is an ashole...
https://www.vuplus-support.org/wbb4/index.php?thread/142192-astra-19-2e-settings-free-iptv-ipradio-ipwebcam/&postID=2088134#post2088134

Here the older threads:

https://www.vuplus-support.org/wbb4/index.php?thread/141496-ip-web-radio-userbouquets/&s=4f5112d7c42d50ed36d66ef55ffc0fb106e9efed

https://www.vuplus-support.org/wbb4/index.php?thread/141764-iptv-free-web-tv-webcam-userbouquets/&s=4f5112d7c42d50ed36d66ef55ffc0fb106e9efed

**Comment by maggyskins** [comment]
Lamento que este hombre sea demasiado primitivo y sólo conozca el insulto y la carnaza en internet. ¡No me rebajaré a su nivel!

**Comment by Raspifan2020** [comment]
> 
> 
> Lamento que este hombre sea demasiado primitivo y sólo conozca el insulto y la carnaza en internet. ¡No me rebajaré a su nivel!

Haha, du hinterhältiger Kerl, du begibst dich ja auf das Niveau der Idioten, die nichts selber gebacken bekommen, deshalb klaust du dir ja alles von anderen Sites zusammen. Du bist eine Schande für die IPTV-Szene und auch für dieses VU+ Forum! Es haben mittlerweile mehrere Leute ein Auge auf dein Treiben, die Rechnung... kommt immer hinterher, wenn es zu spät ist! Verarschst täglich die eigenen User im Forum. Erwähnst dan FluxusTV, damit hast du dich sowas von lächerlich gemacht! Auf der Website passiert nämlich schon seit langer Zeit NICHTS mehr. Höre einfach auf, die Arbeit anderer zu klauen und die leute im Forum damit zu verarschen. Du bist einfach nur armseelig und kannst nichts selber machen!

**Comment by HelmerLuzo** [comment]
La cosa es muy fácil de entender.

Si yo no quisiera que "mis" listas las usaran en otros sitios, no las publicaría.

Con una vez que digan que esa lista es de "Helmer Luzo", me doy por satisfecho, pero no me quita el sueño si no lo hacen.

Esto lo hago porque me gusta aprender.

Y yo pude ver como puso mi nombre al lado de las listas de PlutoTV, no dijo que era suyo.

Fin del problema.

**Comment by Free-IPTV** [comment]
> 
> 
> La cosa es muy fácil de entender.
> 
> Si yo no quisiera que "mis" listas las usaran en otros sitios, no las publicaría.
> 
> Con una vez que digan que esa lista es de "Helmer Luzo", me doy por satisfecho, pero no me quita el sueño si no lo hacen.
> 
> Esto lo hago porque me gusta aprender.
> 
> Y yo pude ver como puso mi nombre al lado de las listas de PlutoTV, no dijo que era suyo.
> 
> Fin del problema.

It's clear in our readme, ONLY for private use but there are always idiots who don't care about rules. Now the stealing is over!
