### ISSUE TITLE
Problema con la estructura m3u

### ISSUE THREAD

**Issue by ElGranFilemon** [HelmerLuzo/PlutoTV_HL#2]
Lo primero, darte las gracias por tu esfuerzo @HelmerLuzo, lo que haces conlleva mucho trabajo. 
No obstante, quiero hacerte saber que en tus listas hay un problema que hace que no sean compatibles con muchos reproductores iptv, por ejemplo, con SSIPTV (el reproductor más común en smart tv). El problema es que en cada línea que comienza por #EXTINF:-1 tú pones dos comas, es decir:
#EXTINF:-1, tvg-id="" tvg-name="" tvg-logo="" group-title="" tvg-chno="", Nombre
Cuando lo correcto, es poner lo siguiente (solo una):
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="" tvg-chno="", Nombre
Esto que parece una tontería, hace que reproductores como SSIPT crean que lo que hay detrás de la primera coma sea el nombre a mostrar, y la url del stream no lo detectan, por lo que las listas quedan inservibles. Puedes comprobarlo con SSIPT, al menos en televisores LG con sistema Netcast es así. Está claro que en el software que usas se ve todo correctamente, pero si descargas cualquier lista m3u de terceros podrás ver que **los parámetros** no se separan con coma después de "#EXTINF:-1" ya que la lista queda inservible y es una pena (solo se pone una coma por línea para indicar el nombre a mostrar al usuario). Por favor, en cualquier editor de texto reemplaza "#EXTINF:-1," por "#EXTINF:-1" y mantén la segunda coma para indicar cuando comienza el nombre a mostrar. Si lo haces así, tu software para visualizar IPTV va a seguir funcionando, y los demás programas que no son capaces de descifrar tus listas m3u también van a funcionar bien. Es una pena que tu trabajo no se pueda disfrutar por un problema de compatibilidad tan facilmente subsanable.
Muchas gracias de nuevo por tu trabajo.

**Comment by HelmerLuzo** [comment]
Totalmente de acuerdo. Esa coma lleva ahí desde el principio y lo cierto es que si no es por ti, hubiera seguido ahí ni se sabe, puesto que nadie lo había reportado hasta ahora.

Ya he corregido el error en los scripts y regenerado los m3u,

**Comment by HelmerLuzo** [comment]
Gracias por avisar.

**Comment by ElGranFilemon** [comment]
@HelmerLuzo Muchísimas gracias a tí por tu esfuerzo.

**Comment by ElGranFilemon** [comment]
Ahora sí. Muchas gracias, todo perfecto.

**Comment by HelmerLuzo** [comment]
En cuanto me des el OK, cierro el issue.

**Comment by HelmerLuzo** [comment]
Hemos escrito los 2 a la vez.

Gracias por el aviso. Como te dije, si tú no me avisas yo no me doy cuenta de esa "," . 

De nuevo, GRACIAS.
